#include <cstdlib>
int main(){
    system("#!/bin/bash");
    system("problem=\"\"");
    system("if [ \"$1\" == \"\" ]; then");
    system("    echo \"problem not given\"");
    system("    exit 1");
    system("fi");
    system("problem=$1");
    system("if [ \"$2\" == \"create\" ]; then");
    system("    if [ -f \"$problem.cpp\" ]; then");
    system("        echo \"already exist\"");
    system("        exit 1");
    system("    fi");
    system("    echo \"#include <iostream>\" > \"$problem.cpp\"");
    system("    echo \"using namespace std;\" >> \"$problem.cpp\"");
    system("    echo \"\" >> \"$problem.cpp\"");
    system("    echo \"int main(){\" >> \"$problem.cpp\"");
    system("    echo \"    ios::sync_with_stdio(false);\" >> \"$problem.cpp\"");
    system("    echo \"    cin.tie(NULL);\" >> \"$problem.cpp\"");
    system("    echo \"    int t;\" >> \"$problem.cpp\"");
    system("    echo \"    cin>>t;\" >> \"$problem.cpp\"");
    system("    echo \"    for(int t_i=0;t_i<t;t_i++){\" >> \"$problem.cpp\"");
    system("    echo \"        \" >> \"$problem.cpp\"");
    system("    echo \"    }\" >> \"$problem.cpp\"");
    system("    echo \"}\" >> \"$problem.cpp\"");
    system("    echo \"\" > \"$problem.input\"");
    system("    echo \"created\"");
    system("    exit 0");
    system("fi");
    system("if [ \"$2\" == \"run\" ]; then");
    system("    if [ ! -f \"$problem\" ]; then");
    system("        echo \"not compiled yet\"");
    system("        exit 1");
    system("    fi");
    system("    if [ ! -f \"$problem.input\" ]; then");
    system("        echo \"input file not ready\"");
    system("        echo \"\" > \"$problem.input\"");
    system("        echo \"input file created\"");
    system("        exit 1");
    system("    fi");
    system("    echo running problem: $problem");
    system("    start=$(date +%s)");
    system("    \"./$problem\" < \"$problem.input\" > \"$problem.output\"");
    system("    ret_code=$?");
    system("    echo executed in $(( $(date +%s) - $start ))s");
    system("    echo terminated returning $ret_code");
    system("    exit 0");
    system("fi");
    system("if [ ! -f \"$problem.cpp\" ]; then");
    system("    echo \"problem not found\"");
    system("    exit 1");
    system("fi");
    system("echo compiling problem $problem:");
    system("g++ -std=c++17 \"$problem.cpp\" -o \"$problem\"");
    system("if [ ! -f \"$problem\" ]; then");
    system("    exit 1");
    system("fi");
    system("if [ ! -f \"$problem.input\" ]; then");
    system("    echo \"input file not ready\"");
    system("    echo \"\" > \"$problem.input\"");
    system("    echo \"input file created\"");
    system("    exit 1");
    system("fi");
    system("echo compilation done!");
    system("echo running:");
    system("start=$(date +%s)");
    system("\"./$problem\" < \"$problem.input\" > \"$problem.output\"");
    system("ret_code=$?");
    system("echo executed in $(( $(date +%s) - $start ))s");
    system("echo terminated returning $ret_code");
    system("exit 0");

}